declare namespace _default {
    export { tagTester };
    export { isBoolean };
    export { isObject };
    export { isNull };
    export { isUndefined };
    export { isElement };
    export { isString };
    export { isNumber };
    export { isDate };
    export { isRegExp };
    export { isError };
    export { isSymbol };
    export { isArrayBuffer };
    export { isFunction };
    export { isDataView };
    export { hasDataViewBug };
    export { isValidDataView };
    export { hasObjectTag };
    export { isBufferLike };
}
export default _default;
export function tagTester(name: any): (obj: any) => boolean;
export function isBoolean(obj: any): boolean;
export function isObject(obj: any): boolean;
export function isNull(obj: any): boolean;
export function isUndefined(obj: any): boolean;
export function isElement(obj: any): boolean;
export function isString(obj: any): boolean;
export function isNumber(obj: any): boolean;
export function isDate(obj: any): boolean;
export function isRegExp(obj: any): boolean;
export function isError(obj: any): boolean;
export function isSymbol(obj: any): boolean;
export function isArrayBuffer(obj: any): boolean;
export function isFunction(obj: any): boolean;
export function isDataView(obj: any): boolean;
export var hasDataViewBug: boolean;
export function isValidDataView(obj: any): boolean;
export function hasObjectTag(obj: any): boolean;
export function isBufferLike(collection: any): boolean;
//# sourceMappingURL=index.d.ts.map