declare namespace _default {
    export { TagTester };
    export { TypeTester };
    export { isString };
    export { isNumber };
    export { isBoolean };
    export { isNull };
    export { isUndefined };
    export { isBigInt };
    export { isSymbol };
    export { isArray };
    export { Uint16Array };
    export { Uint32Array };
    export { Uint8Array };
    export { Uint8ClampedArray };
    export { Int16Array };
    export { Int32Array };
    export { Int8Array };
    export { Float32Array };
    export { Float64Array };
    export { BigInt64Array };
    export { BigUint64Array };
    export { TypedArray };
    export { ArrayBuffer };
    export { SharedArrayBuffer };
    export { isSet };
    export { isObject };
    export { isTagObject };
    export { isFunction };
    export { isAsyncFunction };
    export { isGlobalThis };
    export { isGenerator };
    export { isGeneratorFunction };
    export { isAsyncGenerator };
    export { isAsyncGeneratorFunction };
    export { isPromise };
    export { isError };
    export { isEvalError };
    export { isRangeError };
    export { isReferenceError };
    export { isSyntaxError };
    export { isTypeError };
    export { isURIError };
    export { isAggregateError };
    export { isNonStandardInternalError };
    export { isMap };
    export { isWeakMap };
    export { isWeakRef };
    export { isWeakSet };
    export { isDataView };
    export { isDate };
    export { isJSON };
    export { isProxy };
    export { isReflect };
    export { isRegExp };
    export { isIntl };
    export { isFinalizationRegistry };
    export { isMath };
    export { isFloat };
    export { isNotNaN };
    export { isTrueNaN };
    export { isInfinity };
    export { isAtomics };
    export { isType };
    export { inbuilt };
    export { extendedtypes };
    export { typedefs };
}
export default _default;
export function TagTester(name: any): (obj: any) => boolean;
export function TypeTester(name: any): boolean | ((obj: any) => boolean);
export function isString(obj: any): boolean;
export function isNumber(obj: any): boolean;
export function isBoolean(obj: any): boolean;
export function isNull(obj: any): boolean;
export function isUndefined(obj: any): boolean;
export function isBigInt(obj: any): boolean;
export function isSymbol(obj: any): boolean;
export function isArray(obj: any): boolean;
export function Uint16Array(obj: any): boolean;
export function Uint32Array(obj: any): boolean;
export function Uint8Array(obj: any): boolean;
export function Uint8ClampedArray(obj: any): boolean;
export function Int16Array(obj: any): boolean;
export function Int32Array(obj: any): boolean;
export function Int8Array(obj: any): boolean;
export function Float32Array(obj: any): boolean;
export function Float64Array(obj: any): boolean;
export function BigInt64Array(obj: any): boolean;
export function BigUint64Array(obj: any): boolean;
export function TypedArray(obj: any): boolean;
export function ArrayBuffer(obj: any): boolean;
export function SharedArrayBuffer(obj: any): boolean;
export function isSet(obj: any): boolean;
export function isObject(obj: any): boolean;
export function isTagObject(obj: any): boolean;
export function isFunction(obj: any): boolean;
export function isAsyncFunction(obj: any): boolean;
export function isGlobalThis(obj: any): boolean;
export function isGenerator(obj: any): boolean;
export function isGeneratorFunction(obj: any): boolean;
export function isAsyncGenerator(obj: any): boolean;
export function isAsyncGeneratorFunction(obj: any): boolean;
export function isPromise(obj: any): boolean;
export function isError(obj: any): boolean;
export function isEvalError(obj: any): boolean;
export function isRangeError(obj: any): boolean;
export function isReferenceError(obj: any): boolean;
export function isSyntaxError(obj: any): boolean;
export function isTypeError(obj: any): boolean;
export function isURIError(obj: any): boolean;
export function isAggregateError(obj: any): boolean;
export function isNonStandardInternalError(obj: any): boolean;
export function isMap(obj: any): boolean;
export function isWeakMap(obj: any): boolean;
export function isWeakRef(obj: any): boolean;
export function isWeakSet(obj: any): boolean;
export function isDataView(obj: any): boolean;
export function isDate(obj: any, dateFormat: any): boolean;
export function isJSON(obj: any): boolean;
export function isProxy(obj: any): boolean;
export function isReflect(obj: any): boolean;
export function isRegExp(obj: any): boolean;
export function isIntl(): boolean;
export function isFinalizationRegistry(): void;
export function isMath(): boolean;
export function isFloat(obj: any): void;
export function isNotNaN(obj: any): boolean;
export function isTrueNaN(obj: any): boolean;
export function isInfinity(obj: any): boolean;
export function isAtomics(obj: any): boolean;
export function isType(obj: any, typeStringName: any): boolean;
export let inbuilt: string[];
export let extendedtypes: string[];
export let typedefs: string[];
//# sourceMappingURL=index.d.ts.map